apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -cv -o cvat_helm_build
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cvat
  name: cvat
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: cvat
status:
  loadBalancer: {}
