apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -cv -o cvat_helm_build
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-ui
  name: cvat-ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -cv -o cvat_helm_build
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: cvat-ui
    spec:
      containers:
      - env:
        - name: REACT_APP_API_HOST
          value: localhost
        - name: REACT_APP_API_PORT
          value: "8080"
        - name: REACT_APP_API_PROTOCOL
          value: http
        image: nginx
        name: cvat-ui
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
