apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -cv -o cvat_helm_build
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-redis
  name: cvat-redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -cv -o cvat_helm_build
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: cvat-redis
    spec:
      containers:
      - image: redis:4.0.5-alpine
        name: cvat-redis
        ports:
          - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
