apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -cv -o cvat_helm_build
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cvat
  name: cvat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -cv -o cvat_helm_build
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: cvat
    spec:
      containers:
      - env:
        - name: DJANGO_MODWSGI_EXTRA_ARGS
        - name: UI_PORT
          value: "7080"
        image: cvat
        name: cvat
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /home/django/data
          name: cvat-data
        - mountPath: /home/django/keys
          name: cvat-keys
        - mountPath: /home/django/logs
          name: cvat-logs
        - mountPath: /home/django/models
          name: cvat-models
      restartPolicy: Always
      volumes:
      - name: cvat-data
        persistentVolumeClaim:
          claimName: cvat-data
      - name: cvat-keys
        persistentVolumeClaim:
          claimName: cvat-keys
      - name: cvat-logs
        persistentVolumeClaim:
          claimName: cvat-logs
      - name: cvat-models
        persistentVolumeClaim:
          claimName: cvat-models
status: {}
