apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -cv -o cvat_helm_build
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-db
  name: cvat-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -cv -o cvat_helm_build
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: cvat-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: cvat
        - name: POSTGRES_USER
          value: root
        image: postgres:10.3-alpine
        name: cvat-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: cvat-db
      restartPolicy: Always
      volumes:
      - name: cvat-db
        persistentVolumeClaim:
          claimName: cvat-db
status: {}
